variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_DEPTH: 1
  XDG_CACHE_HOME: "$CI_PROJECT_DIR/.cache"
  VCPKG_FORCE_SYSTEM_BINARIES: 1
  CCACHE_COMPILERCHECK: "content"
  CCACHE_BASEDIR: "$CI_PROJECT_DIR"
  CCACHE_SLOPPINESS: "pch_defines,time_macros"
  CLICOLOR_FORCE: 1
  # CI_DEBUG_SERVICES: "true"
  DOCKER_AUTH_CONFIG: '{
    "auths": {
    "registry.gitlab.com": {
    "auth": "$DOCKER_GITLAB_TOKEN"
    }
    }
    }'
  IMAGE_NAME: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME

default:
  #  tags:
  #    - luhbots
  image: luhsoccer/baguette-ci:0.0.7
  interruptible: true
  before_script:
    - ccache -z -s -p
  after_script:
    - ccache --show-stats
  cache:
    paths:
      - .cache/pip
      - .cache/ccache

stages:
  - workflow
  - version
  - build
  - test
  - lint
  - deploy
  - chores

include:
  - local: .gitlab/default.gitlab-ci.yml
    rules:
      - if: $CREATE_MR != "1"

  - local: .gitlab/docs.gitlab-ci.yml
    rules:
      - if: $CREATE_MR && $CREATE_MR == "1"
        when: never
      - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      - if: $CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push"

  - local: .gitlab/dev-mrs.gitlab-ci.yml
    rules:
      - if: $CREATE_MR && $CREATE_MR == "1"
        when: never
      - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop"

  # - local: ci/main-mrs.gitlab-ci.yml
  #   rules:
  #     - if: $CREATE_MR && $CREATE_MR == "1"
  #       when: never
  #     - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop"

  - local: .gitlab/release-mrs.gitlab-ci.yml
    rules:
      - if: $CREATE_MR && $CREATE_MR == "1"

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_REF_PROTECTED == "true"
